"use client";
import { cloneElement,useEffect,useState} from 'react';
import './globals.css'
import Navibar from '@/components/Navibar';
import FooterBoard from '@/components/Footer';
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col ">
          <Navibar />
          {children}
          <div className='mt-auto'>          
            <FooterBoard />
          </div>
        </div>
      </body>
    </html>
  );
}
